language: java
dist: xenial
sudo: false

install:
  - mvn --projects '!semantic-annotator-console-delivery' install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

addons:
  sonarcloud:
    organization: "clecoq75-github"

script:
  - mvn --projects '!semantic-annotator-console-delivery' clean install -B
  - mvn --projects '!semantic-annotator-console-delivery' clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=cle.nlp:semantic-annotator

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'