language: java

dist: trusty

jdk:
  - oraclejdk11

install:
  - mvn --projects '!semantic-annotator-console-delivery' install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

addons:
  sonarcloud:
    organization: "clecoq75-github"

script:
  - mvn --projects '!semantic-annotator-console-delivery' test -B
  - mvn --projects '!semantic-annotator-console-delivery' clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
